databases:
  - name: exclusive-platform-db
    databaseName: exclusive_platform
    user: exclusive_user
    plan: free

services:
  - type: web
    name: exclusive-platform
    env: docker
    plan: free
    buildCommand: ""
    envVars:
      - key: AUTORUN_ENABLED
        value: true
      - key: AUTORUN_LARAVEL_MIGRATION
        value: true
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: APP_URL
        value: https://exclusive-platform.onrender.com
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: exclusive-platform-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: exclusive-platform-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: exclusive-platform-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: exclusive-platform-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: exclusive-platform-db
          property: password
